const form = document.getElementById("userForm")
const userName = document.getElementById("name")
const userMail = document.getElementById("email") 
const userPassword = document.getElementById("password") 
const welcomeMsg = document.getElementById("message")